<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IdentidadeOrgaosSeeder extends Seeder
{
    public function run()
    {
        //criando Genero
        DB::table('identidade_orgaos')->insert([
            ['sigla' => 'ABNC', 'name' => 'Academia Brasileira de Neurocirurgia'],
            ['sigla' => 'AGU', 'name' => 'Advocacia-Geral da União'],
            ['sigla' => 'ANAC', 'name' => 'Agência Nacional de Aviação Civil'],
            ['sigla' => 'CAER', 'name' => 'Clube de Aeronáutica'],
            ['sigla' => 'CAU', 'name' => 'Conselho de Arquitetura e Urbanismo'],
            ['sigla' => 'CBM', 'name' => 'Corpo de Bombeiro Militar'],
            ['sigla' => 'CFA', 'name' => 'Conselho Federal Administração'],
            ['sigla' => 'CFB', 'name' => 'Conselho Federal de Biblioteconomia'],
            ['sigla' => 'CFBIO', 'name' => 'Conselho Federal de Biologia'],
            ['sigla' => 'CFBM', 'name' => 'Conselho Federal de Biomedicina'],
            ['sigla' => 'CFC', 'name' => 'Conselho Federal de Contabilidade'],
            ['sigla' => 'CFESS', 'name' => 'Conselho Federal de Serviço Social'],
            ['sigla' => 'CFF', 'name' => 'Conselho Regional de Farmácia'],
            ['sigla' => 'CFFA', 'name' => 'Conselho Federal de Fonoaudiologia'],
            ['sigla' => 'CFM', 'name' => 'Conselho Federal de Medicina'],
            ['sigla' => 'CFMV', 'name' => 'Conselho Federal de Medicina Veterinária'],
            ['sigla' => 'CFN', 'name' => 'Conselho Federal de Nutrição'],
            ['sigla' => 'CFO', 'name' => 'Conselho Federal de Odontologia'],
            ['sigla' => 'CFP', 'name' => 'Conselho Federal de Psicologia'],
            ['sigla' => 'CFQ', 'name' => 'Conselho Regional de Química'],
            ['sigla' => 'CFT', 'name' => 'Conselho Federal dos Técnicos Industriais'],
            ['sigla' => 'CFTA', 'name' => 'Conselho Federal dos Técnicos Agrícolas'],
            ['sigla' => 'CGPI', 'name' => 'Coordenação Geral de Privilégios e Imunidades'],
            ['sigla' => 'CGPMAF', 'name' => 'Coordenadoria Geral de Polícia Marítima, Aeronáutica e de Fronteiras'],
            ['sigla' => 'CIPC', 'name' => 'Centro de Inteligência da Polícia Civil'],
            ['sigla' => 'CNIG', 'name' => 'Conselho Nacional de Imigração'],
            ['sigla' => 'CNT', 'name' => 'Confederação Nacional do Transporte'],
            ['sigla' => 'CNTV', 'name' => 'Confederação Nacional de Vigilantes & Prestadores de Serviços'],
            ['sigla' => 'COFECI', 'name' => 'Conselho Federal de Corretores de Imóveis'],
            ['sigla' => 'COFECON', 'name' => 'Conselho Federal de Economia'],
            ['sigla' => 'COFEM', 'name' => 'Conselho Federal de Museologia'],
            ['sigla' => 'COFEN', 'name' => 'Conselho Federal de Enfermagem'],
            ['sigla' => 'COFFITO', 'name' => 'Conselho Regional de Fisioterapia e Terapia Ocupacional'],
            ['sigla' => 'COMAER', 'name' => 'Comando da Aeronáutica'],
            ['sigla' => 'CONFE', 'name' => 'Conselho Federal de Estatística'],
            ['sigla' => 'CONFEA', 'name' => 'Conselho Federal de Engenharia e Agronomia'],
            ['sigla' => 'CONFEF', 'name' => 'Conselho Federal de Educação Física'],
            ['sigla' => 'CONFERE', 'name' => 'Conselho Federal dos Representantes Comerciais'],
            ['sigla' => 'CONRE', 'name' => 'Conselho Regional de Estatística'],
            ['sigla' => 'CONRERP', 'name' => 'Conselho Federal de Profissionais de Relações Públicas'],
            ['sigla' => 'CORE', 'name' => 'Conselho Regional dos Representantes Comerciais'],
            ['sigla' => 'CORECON', 'name' => 'Conselho Regional de Economia'],
            ['sigla' => 'COREM', 'name' => 'Conselho Regional de Museologia'],
            ['sigla' => 'COREN', 'name' => 'Conselho Regional de Enfermagem'],
            ['sigla' => 'CRA', 'name' => 'Conselho Regional de Administração'],
            ['sigla' => 'CRAS', 'name' => 'Centro de Referência de Assistência Social'],
            ['sigla' => 'CRB', 'name' => 'Conselho Regional de Biblioteconomia'],
            ['sigla' => 'CRBIO', 'name' => 'Conselho Regional de Biologia'],
            ['sigla' => 'CRBM', 'name' => 'Conselho Regional de Biomedicina'],
            ['sigla' => 'CRC', 'name' => 'Conselho Regional de Contabilidade'],
            ['sigla' => 'CREA', 'name' => 'Conselho Regional de Engenharia e Agronomia'],
            ['sigla' => 'CRECI', 'name' => 'Conselho Regional de Corretores de Imóveis'],
            ['sigla' => 'CREF', 'name' => 'Conselho Regional de Educação Física'],
            ['sigla' => 'CREFITO', 'name' => 'Conselho Regional de Fisioterapia e Terapia Ocupacional'],
            ['sigla' => 'CRESS', 'name' => 'Conselho Regional de Serviço Social'],
            ['sigla' => 'CRF', 'name' => 'Conselho Regional de Farmácia'],
            ['sigla' => 'CRFA', 'name' => 'Conselho Regional de Fonoaudiologia'],
            ['sigla' => 'CRM', 'name' => 'Conselho Regional de Medicina'],
            ['sigla' => 'CRMV', 'name' => 'Conselho Regional de Medicina Veterinária'],
            ['sigla' => 'CRN', 'name' => 'Conselho Regional de Nutrição'],
            ['sigla' => 'CRO', 'name' => 'Conselho Regional de Odontologia'],
            ['sigla' => 'CRP', 'name' => 'Conselho Regional de Psicologia'],
            ['sigla' => 'CRPRE', 'name' => 'Conselho Regional de Profissionais de Relações Públicas'],
            ['sigla' => 'CRQ', 'name' => 'Conselho Regional de Química'],
            ['sigla' => 'CRT', 'name' => 'Conselho Regional dos Técnicos Industriais'],
            ['sigla' => 'CRTA', 'name' => 'Conselho Regional de Técnicos de Administração'],
            ['sigla' => 'CTPS', 'name' => 'Carteira de Trabalho e Previdência Social'],
            ['sigla' => 'CV', 'name' => 'Cartório Civil'],
            ['sigla' => 'DELEMIG', 'name' => 'Delegacia de Polícia de Imigração'],
            ['sigla' => 'DETRAN', 'name' => 'Departamento Estadual de Trânsito'],
            ['sigla' => 'DGPC', 'name' => 'Diretoria Geral da Polícia Civil'],
            ['sigla' => 'DIC', 'name' => 'Diretoria de Identificação Civil'],
            ['sigla' => 'DICC', 'name' => 'Diretoria de Identificação Civil e Criminal'],
            ['sigla' => 'DIREX', 'name' => 'Diretoria Executiva'],
            ['sigla' => 'DPF', 'name' => 'Departamento de Polícia Federal'],
            ['sigla' => 'DPMAF', 'name' => 'Divisão de Polícia Marítima, Aérea e de Fronteiras'],
            ['sigla' => 'DPT', 'name' => 'Departamento de Polícia Técnica Geral'],
            ['sigla' => 'DPTC', 'name' => 'Departamento de Polícia Técnico Científica'],
            ['sigla' => 'DREX', 'name' => 'Delegacia Regional Executiva'],
            ['sigla' => 'DRT', 'name' => 'Delegacia Regional do Trabalho'],
            ['sigla' => 'EB', 'name' => 'Exército Brasileiro'],
            ['sigla' => 'FAB', 'name' => 'Força Aérea Brasileira'],
            ['sigla' => 'FENAJ', 'name' => 'Federação Nacional dos Jornalistas'],
            ['sigla' => 'FGTS', 'name' => 'Fundo de Garantia do Tempo de Serviço'],
            ['sigla' => 'FIPE', 'name' => 'Fundação Instituto de Pesquisas Econômicas'],
            ['sigla' => 'FLS', 'name' => 'Fundação Lyndolpho Silva'],
            ['sigla' => 'FUNAI', 'name' => 'Fundação Nacional do Índio'],
            ['sigla' => 'GEJSP', 'name' => 'Gerência de Estado de Justiça, Segurança Pública e Cidadania'],
            ['sigla' => 'GEJSPC', 'name' => 'Gerência de Estado de Justiça, Segurança Pública e Cidadania'],
            ['sigla' => 'GEJUSPC', 'name' => 'Gerência de Estado de Justiça, Segurança Pública e Cidadania'],
            ['sigla' => 'GESP', 'name' => 'Gerência de Estado de Segurança Pública'],
            ['sigla' => 'GOVGO', 'name' => 'Governo do Estado de Goiás'],
            ['sigla' => 'I CLA', 'name' => 'Carteira de Identidade Classista'],
            ['sigla' => 'ICP', 'name' => 'Instituto de Polícia Científica'],
            ['sigla' => 'IDAMP', 'name' => 'Instituto de Identificação Dr. Aroldo Mendes Paiva'],
            ['sigla' => 'IFP', 'name' => 'Instituto Félix Pacheco'],
            ['sigla' => 'IGP', 'name' => 'Instituto Geral de Perícias'],
            ['sigla' => 'IIACM', 'name' => 'Instituto de Identificação Aderson Conceição de Melo'],
            ['sigla' => 'IICC', 'name' => 'Instituto de Identificação Civil e Criminal'],
            ['sigla' => 'IICCECF', 'name' => 'Instituto de Identificação Civil e Criminal Engrácia da Costa Francisco'],
            ['sigla' => 'IICM', 'name' => 'Instituto de Identificação Carlos Menezes'],
            ['sigla' => 'IIGP', 'name' => 'Instituto de Identificação Gonçalo Pereira'],
            ['sigla' => 'IIJDM', 'name' => 'Instituto de Identificação João de Deus Martins'],
            ['sigla' => 'IIPC', 'name' => 'Instituto de Identificação da Polícia Civil'],
            ['sigla' => 'IIPC', 'name' => 'Instituto de Identificação Pedro Mello'],
            ['sigla' => 'IIRGD', 'name' => 'Instituto de Identificação Ricardo Gumbleton Daunt'],
            ['sigla' => 'IIRHM', 'name' => 'Instituto de Identificação Raimundo Hermínio de Melo'],
            ['sigla' => 'IITB', 'name' => 'Instituto de Identificação Tavares Buril'],
            ['sigla' => 'IML', 'name' => 'Instituto Médico-Legal'],
            ['sigla' => 'INI', 'name' => 'Instituto Nacional de Identificação'],
            ['sigla' => 'IPF', 'name' => 'Instituto Pereira Faustino'],
            ['sigla' => 'ITCP', 'name' => 'Instituto Técnico-Científico de Perícia'],
            ['sigla' => 'ITEP', 'name' => 'Instituto Técnico-Científico de Perícia'],
            ['sigla' => 'MAER', 'name' => 'Ministério da Aeronáutica'],
            ['sigla' => 'MB', 'name' => 'Marinha do Brasil'],
            ['sigla' => 'MD', 'name' => 'Ministério da Defesa'],
            ['sigla' => 'MDS', 'name' => 'Ministério da Cidadania'],
            ['sigla' => 'MEC', 'name' => 'Ministério da Educação e Cultura'],
            ['sigla' => 'MEX', 'name' => 'Ministério do Exército'],
            ['sigla' => 'MINDEF', 'name' => 'Ministério da Defesa'],
            ['sigla' => 'MJ', 'name' => 'Ministério da Justiça'],
            ['sigla' => 'MM', 'name' => 'Ministério da Marinha'],
            ['sigla' => 'MMA', 'name' => 'Ministério da Marinha'],
            ['sigla' => 'MPAS', 'name' => 'Ministério da Previdência e Assistência Social'],
            ['sigla' => 'MPE', 'name' => 'Ministério Público Estadual'],
            ['sigla' => 'MPF', 'name' => 'Ministério Público Federal'],
            ['sigla' => 'MPT', 'name' => 'Ministério Público do Trabalho'],
            ['sigla' => 'MRE', 'name' => 'Ministério das Relações Exteriores'],
            ['sigla' => 'MT', 'name' => 'Ministério do Trabalho'],
            ['sigla' => 'MTE', 'name' => 'Ministério da Economia'],
            ['sigla' => 'MTPS', 'name' => 'Ministério do Trabalho e Previdência Social'],
            ['sigla' => 'NUMIG', 'name' => 'Núcleo de Polícia de Imigração'],
            ['sigla' => 'OAB', 'name' => 'Ordem dos Advogados do Brasil'],
            ['sigla' => 'OMB', 'name' => 'Ordens dos Músicos do Brasil'],
            ['sigla' => 'PC', 'name' => 'Polícia Civil'],
            ['sigla' => 'PF', 'name' => 'Polícia Federal'],
            ['sigla' => 'PGFN', 'name' => 'Procuradoria Geral da Fazenda Nacional'],
            ['sigla' => 'PM', 'name' => 'Polícia Militar'],
            ['sigla' => 'POLITEC', 'name' => 'Perícia Oficial e Identificação Técnica'],
            ['sigla' => 'PRF', 'name' => 'Polícia Rodoviária Federal'],
            ['sigla' => 'PTC', 'name' => 'Polícia Tecnico-Científica'],
            ['sigla' => 'SCC', 'name' => 'Secretaria de Estado da Casa Civil'],
            ['sigla' => 'SCJDS', 'name' => 'Secretaria Coordenadora de Justiça e Defesa Social'],
            ['sigla' => 'SDS', 'name' => 'Secretaria de Defesa Social'],
            ['sigla' => 'SECC', 'name' => 'Secretaria de Estado da Casa Civil'],
            ['sigla' => 'SECCDE', 'name' => 'Secretaria de Estado da Casa Civil e Desenvolvimento Econômico'],
            ['sigla' => 'SEDS', 'name' => 'Secretaria de Estado da Defesa Social'],
            ['sigla' => 'SEGUP', 'name' => 'Secretaria de Estado da Segurança Pública e da Defesa Social'],
            ['sigla' => 'SEJSP', 'name' => 'Secretaria de Estado de Justiça e Segurança Pública'],
            ['sigla' => 'SEJUC', 'name' => 'Secretaria de Estado da Justica'],
            ['sigla' => 'SEJUSP', 'name' => 'Secretaria de Estado de Justiça e Segurança Pública'],
            ['sigla' => 'SEPC', 'name' => 'Secretaria de Estado da Polícia Civil'],
            ['sigla' => 'SES', 'name' => 'Secretaria de Estado da Segurança'],
            ['sigla' => 'SESC', 'name' => 'Secretaria de Estado da Segurança e Cidadania'],
            ['sigla' => 'SESDC', 'name' => 'Secretaria de Estado da Segurança, Defesa e Cidadania'],
            ['sigla' => 'SESDEC', 'name' => 'Secretaria de Estado da Segurança, Defesa e Cidadania'],
            ['sigla' => 'SESEG', 'name' => 'Secretaria Estadual de Segurança'],
            ['sigla' => 'SESP', 'name' => 'Secretaria de Estado da Segurança Pública'],
            ['sigla' => 'SESPAP', 'name' => 'Secretaria de Estado da Segurança Pública e Administração Penitenciária'],
            ['sigla' => 'SESPDC', 'name' => 'Secretaria de Estado de Segurança Publica e Defesa do Cidadão'],
            ['sigla' => 'SESPDS', 'name' => 'Secretaria de Estado de Segurança Pública e Defesa Social'],
            ['sigla' => 'SGPC', 'name' => 'Superintendência Geral de Polícia Civil'],
            ['sigla' => 'SGPJ', 'name' => 'Superintendência Geral de Polícia Judiciária'],
            ['sigla' => 'SIM', 'name' => 'Serviço de Identificação da Marinha'],
            ['sigla' => 'SJ', 'name' => 'Secretaria da Justiça'],
            ['sigla' => 'SJCDH', 'name' => 'Secretaria da Justiça e dos Direitos Humanos'],
            ['sigla' => 'SJDS', 'name' => 'Secretaria Coordenadora de Justiça e Defesa Social'],
            ['sigla' => 'SJS', 'name' => 'Secretaria da Justiça e Segurança'],
            ['sigla' => 'SJTC', 'name' => 'Secretaria da Justiça do Trabalho e Cidadania'],
            ['sigla' => 'SJTS', 'name' => 'Secretaria da Justiça do Trabalho e Segurança'],
            ['sigla' => 'SNJ', 'name' => 'Secretaria Nacional de Justiça / Departamento de Estrangeiros'],
            ['sigla' => 'SPMAF', 'name' => 'Serviço de Polícia Marítima, Aérea e de Fronteiras'],
            ['sigla' => 'SPTC', 'name' => 'Secretaria de Polícia Técnico-Científica'],
            ['sigla' => 'SRDPF', 'name' => 'Superintendência Regional do Departamento de Polícia Federal'],
            ['sigla' => 'SRF', 'name' => 'Receita Federal'],
            ['sigla' => 'SRTE', 'name' => 'Superintendência Regional do Trabalho'],
            ['sigla' => 'SSDC', 'name' => 'Secretaria da Segurança, Defesa e Cidadania'],
            ['sigla' => 'SSDS', 'name' => 'Secretaria da Segurança e da Defesa Social'],
            ['sigla' => 'SSI', 'name' => 'Secretaria de Segurança e Informações'],
            ['sigla' => 'SSP', 'name' => 'Secretaria de Segurança Pública'],
            ['sigla' => 'SSPCGP', 'name' => 'Secretaria de Segurança Pública e Coordenadoria Geral de Perícias'],
            ['sigla' => 'SSPDC', 'name' => 'Secretaria de Segurança Pública e Defesa do Cidadão'],
            ['sigla' => 'SSPDS', 'name' => 'Secretaria de Segurança Pública e Defesa Social'],
            ['sigla' => 'SSPPC', 'name' => 'Secretaria de Segurança Pública Polícia Civil'],
            ['sigla' => 'SUSEP', 'name' => 'Superintendência de Seguros Privados'],
            ['sigla' => 'SUSEPE', 'name' => 'Superintendência dos Serviços Penitenciários'],
            ['sigla' => 'TJ', 'name' => 'Tribunal de Justiça'],
            ['sigla' => 'TJAEM', 'name' => 'Tribunal Arbitral e Mediação dos Estados Brasileiros'],
            ['sigla' => 'TRE', 'name' => 'Tribunal Regional Eleitoral'],
            ['sigla' => 'TRF', 'name' => 'Tribunal Regional Federal'],
            ['sigla' => 'TSE', 'name' => 'Tribunal Superior Eleitoral']
        ]);
    }
}
