<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NacionalidadesSeeder extends Seeder
{
    public function run()
    {
        DB::table('nacionalidades')->insert([
            ['nation' => 'Antígua e Barbuda', 'name' => 'Antiguano'],
            ['nation' => 'Argentina', 'name' => 'Argentino'],
            ['nation' => 'Bahamas', 'name' => 'Bahamense'],
            ['nation' => 'Barbados', 'name' => 'Barbadiano, barbadense'],
            ['nation' => 'Belize', 'name' => 'Belizenho'],
            ['nation' => 'Bolívia', 'name' => 'Boliviano'],
            ['nation' => 'Brasil', 'name' => 'Brasileiro'],
            ['nation' => 'Chile', 'name' => 'Chileno'],
            ['nation' => 'Colômbia', 'name' => 'Colombiano'],
            ['nation' => 'Costa Rica', 'name' => 'Costarriquenho'],
            ['nation' => 'Cuba', 'name' => 'Cubano'],
            ['nation' => 'Dominica', 'name' => 'Dominicano'],
            ['nation' => 'Equador', 'name' => 'Equatoriano'],
            ['nation' => 'El Salvador', 'name' => 'Salvadorenho'],
            ['nation' => 'Granada', 'name' => 'Granadino'],
            ['nation' => 'Guatemala', 'name' => 'Guatemalteco'],
            ['nation' => 'Guiana', 'name' => 'Guianês'],
            ['nation' => 'Guiana Francesa', 'name' => 'Guianense'],
            ['nation' => 'Haiti', 'name' => 'Haitiano'],
            ['nation' => 'Honduras', 'name' => 'Hondurenho'],
            ['nation' => 'Jamaica', 'name' => 'Jamaicano'],
            ['nation' => 'México', 'name' => 'Mexicano'],
            ['nation' => 'Nicarágua', 'name' => 'Nicaraguense'],
            ['nation' => 'Panamá', 'name' => 'Panamenho'],
            ['nation' => 'Paraguai', 'name' => 'Paraguaio'],
            ['nation' => 'Peru', 'name' => 'Peruano'],
            ['nation' => 'Porto Rico', 'name' => 'Portorriquenho'],
            ['nation' => 'República Dominicana', 'name' => 'Dominicana'],
            ['nation' => 'São Cristóvão e Nevis', 'name' => 'São-cristovense'],
            ['nation' => 'São Vicente e Granadinas', 'name' => 'São-vicentino'],
            ['nation' => 'Santa Lúcia', 'name' => 'Santa-lucense'],
            ['nation' => 'Suriname', 'name' => 'Surinamês'],
            ['nation' => 'Trinidad e Tobago', 'name' => 'Trindadense'],
            ['nation' => 'Uruguai', 'name' => 'Uruguaio'],
            ['nation' => 'Venezuela', 'name' => 'Venezuelano'],
            ['nation' => 'Alemanha', 'name' => 'Alemão'],
            ['nation' => 'Áustria', 'name' => 'Austríaco'],
            ['nation' => 'Bélgica', 'name' => 'Belga'],
            ['nation' => 'Croácia', 'name' => 'Croata'],
            ['nation' => 'Dinamarca', 'name' => 'Dinamarquês'],
            ['nation' => 'Eslováquia', 'name' => 'Eslovaco'],
            ['nation' => 'Eslovênia', 'name' => 'Esloveno'],
            ['nation' => 'Espanha', 'name' => 'Espanhol'],
            ['nation' => 'França', 'name' => 'Francês'],
            ['nation' => 'Grécia', 'name' => 'Grego'],
            ['nation' => 'Hungria', 'name' => 'Húngaro'],
            ['nation' => 'Irlanda', 'name' => 'Irlandês'],
            ['nation' => 'Itália', 'name' => 'Italiano'],
            ['nation' => 'Noruega', 'name' => 'Noruego'],
            ['nation' => 'Países Baixos', 'name' => 'Holandês'],
            ['nation' => 'Polônia', 'name' => 'Polonês'],
            ['nation' => 'Portugal', 'name' => 'Português'],
            ['nation' => 'Reino Unido', 'name' => 'Britânico'],
            ['nation' => 'Inglaterra', 'name' => 'Inglês'],
            ['nation' => 'País de Gales', 'name' => 'Galês'],
            ['nation' => 'Escócia', 'name' => 'Escocês'],
            ['nation' => 'Romênia', 'name' => 'Romeno'],
            ['nation' => 'Rússia', 'name' => 'Russo'],
            ['nation' => 'Sérvio', 'name' => 'Sérvio'],
            ['nation' => 'Suécia', 'name' => 'Sueco'],
            ['nation' => 'Suíça', 'name' => 'Suíço'],
            ['nation' => 'Turquia', 'name' => 'Turco'],
            ['nation' => 'Ucrânia', 'name' => 'Ucraniano'],
            ['nation' => 'Estados Unidos', 'name' => 'Americano'],
            ['nation' => 'Canadá', 'name' => 'Canadense'],
            ['nation' => 'Angola', 'name' => 'Angolano'],
            ['nation' => 'Moçambique', 'name' => 'Moçambicano'],
            ['nation' => 'África do Sul', 'name' => 'Sul-africano'],
            ['nation' => 'Zimbabue', 'name' => 'Zimbabuense'],
            ['nation' => 'Argélia', 'name' => 'Argélia'],
            ['nation' => 'Comores', 'name' => 'Comorense'],
            ['nation' => 'Egito', 'name' => 'Egípcio'],
            ['nation' => 'Líbia', 'name' => 'Líbio'],
            ['nation' => 'Marrocos', 'name' => 'Marroquino'],
            ['nation' => 'Gana', 'name' => 'Ganés'],
            ['nation' => 'Quênia', 'name' => 'Queniano'],
            ['nation' => 'Ruanda', 'name' => 'Ruandês'],
            ['nation' => 'Uganda', 'name' => 'Ugandense'],
            ['nation' => 'Botsuana', 'name' => 'Bechuano'],
            ['nation' => 'Costa do Marfim', 'name' => 'Marfinense'],
            ['nation' => 'Camarões', 'name' => 'Camaronense'],
            ['nation' => 'Nigéria', 'name' => 'Nigeriano'],
            ['nation' => 'Somália', 'name' => 'Somali'],
            ['nation' => 'Austrália', 'name' => 'Australiano'],
            ['nation' => 'Nova Zelândia', 'name' => 'Neozelandês'],
            ['nation' => 'Afeganistão', 'name' => 'Afegão'],
            ['nation' => 'Arábia Saudita', 'name' => 'Saudita'],
            ['nation' => 'Armênia', 'name' => 'Armeno'],
            ['nation' => 'Armeno', 'name' => 'Bangladesh'],
            ['nation' => 'China', 'name' => 'Chinês'],
            ['nation' => 'Coréia do Norte', 'name' => 'Norte-coreano, coreano'],
            ['nation' => 'Coréia do Sul', 'name' => 'Sul-coreano, coreano'],
            ['nation' => 'Índia', 'name' => 'Indiano'],
            ['nation' => 'Indonésia', 'name' => 'Indonésio'],
            ['nation' => 'Iraque', 'name' => 'Iraquiano'],
            ['nation' => 'Irã', 'name' => 'Iraniano'],
            ['nation' => 'Israel', 'name' => 'Israelita'],
            ['nation' => 'Japão', 'name' => 'Japonês'],
            ['nation' => 'Malásia', 'name' => 'Malaio'],
            ['nation' => 'Nepal', 'name' => 'Nepalês'],
            ['nation' => 'Omã', 'name' => 'Omanense'],
            ['nation' => 'Paquistão', 'name' => 'Paquistanês'],
            ['nation' => 'Palestina', 'name' => 'Palestino'],
            ['nation' => 'Qatar', 'name' => 'Qatarense'],
            ['nation' => 'Síria', 'name' => 'Sírio'],
            ['nation' => 'Sri Lanka', 'name' => 'Cingalês'],
            ['nation' => 'Tailândia', 'name' => 'Tailandês'],
            ['nation' => 'Timor-Leste', 'name' => 'Timorense, maubere'],
            ['nation' => 'Emirados Árabes Unidos', 'name' => 'Árabe, emiratense'],
            ['nation' => 'Vietnã', 'name' => 'Vietnamita'],
            ['nation' => 'Iêmen', 'name' => 'Iemenita']
        ]);
    }
}
