<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TelephoneDdisSeeder extends Seeder
{
    public function run()
    {
        DB::table('telephone_ddis')->insert([
            ['nation' => 'Afghanistão', 'ddi' => '93'],
            ['nation' => 'África do Sul', 'ddi' => '27'],
            ['nation' => 'Albânia', 'ddi' => '355'],
            ['nation' => 'Alemanha', 'ddi' => '49'],
            ['nation' => 'Andora', 'ddi' => '376'],
            ['nation' => 'Angola', 'ddi' => '244'],
            ['nation' => 'Anguilla', 'ddi' => '1 264'],
            ['nation' => 'Antarctica', 'ddi' => '672'],
            ['nation' => 'Antígua e Barbuda', 'ddi' => '1 268'],
            ['nation' => 'Argentina', 'ddi' => '54'],
            ['nation' => 'Argélia', 'ddi' => '213'],
            ['nation' => 'Arménia', 'ddi' => '374'],
            ['nation' => 'Aruba', 'ddi' => '297'],
            ['nation' => 'Arábia Saudita', 'ddi' => '966'],
            ['nation' => 'Austrália', 'ddi' => '61'],
            ['nation' => 'Áustria', 'ddi' => '43'],
            ['nation' => 'Azerbaijão', 'ddi' => '994'],
            ['nation' => 'Bahamas', 'ddi' => '1 242'],
            ['nation' => 'Bahrein', 'ddi' => '973'],
            ['nation' => 'Bangladesh', 'ddi' => '880'],
            ['nation' => 'Barbados', 'ddi' => '1 246'],
            ['nation' => 'Bélgica', 'ddi' => '32'],
            ['nation' => 'Belize', 'ddi' => '501'],
            ['nation' => 'Benim', 'ddi' => '229'],
            ['nation' => 'Bermuda', 'ddi' => '1 441'],
            ['nation' => 'Butão', 'ddi' => '975'],
            ['nation' => 'Bielorrússia', 'ddi' => '375'],
            ['nation' => 'Bolívia', 'ddi' => '591'],
            ['nation' => 'Bósnia e Herzegovina', 'ddi' => '387'],
            ['nation' => 'Botswana', 'ddi' => '267'],
            ['nation' => 'Brasil', 'ddi' => '55'],
            ['nation' => 'British Indian Ocean Territory', 'ddi' => ''],
            ['nation' => 'Brunei', 'ddi' => '673'],
            ['nation' => 'Bulgária', 'ddi' => '359'],
            ['nation' => 'Burkina Faso', 'ddi' => '226'],
            ['nation' => 'Myanmar (Burma)', 'ddi' => '95'],
            ['nation' => 'Burundi', 'ddi' => '257'],
            ['nation' => 'Camarões', 'ddi' => '237'],
            ['nation' => 'Cabo Verde', 'ddi' => '238'],
            ['nation' => 'Camboja', 'ddi' => '855'],
            ['nation' => 'Canadá', 'ddi' => '1'],
            ['nation' => 'Catar', 'ddi' => '974'],
            ['nation' => 'Chad', 'ddi' => '235'],
            ['nation' => 'Chile', 'ddi' => '56'],
            ['nation' => 'China', 'ddi' => '86'],
            ['nation' => 'Chipre', 'ddi' => '357'],
            ['nation' => 'Christmas Island', 'ddi' => '61'],
            ['nation' => 'Cingapura', 'ddi' => '65'],
            ['nation' => 'Colômbia', 'ddi' => '57'],
            ['nation' => 'Comores', 'ddi' => '269'],
            ['nation' => 'Coreia do Norte', 'ddi' => '850'],
            ['nation' => 'Coreia do Sul', 'ddi' => '82'],
            ['nation' => 'Costa do Marfim', 'ddi' => '225'],
            ['nation' => 'Costa Rica', 'ddi' => '506'],
            ['nation' => 'Croácia', 'ddi' => '385'],
            ['nation' => 'Cuba', 'ddi' => '53'],
            ['nation' => 'Dinamarca', 'ddi' => '45'],
            ['nation' => 'Djibouti', 'ddi' => '253'],
            ['nation' => 'Dominica', 'ddi' => '1 767'],
            ['nation' => 'Egito', 'ddi' => '20'],
            ['nation' => 'El Salvador', 'ddi' => '503'],
            ['nation' => 'Emirados Árabes Unidos', 'ddi' => '971'],
            ['nation' => 'Equador', 'ddi' => '593'],
            ['nation' => 'Eritreia', 'ddi' => '291'],
            ['nation' => 'Estónia', 'ddi' => '372'],
            ['nation' => 'Espanha', 'ddi' => '34'],
            ['nation' => 'Etiópia', 'ddi' => '251'],
            ['nation' => 'Fiji', 'ddi' => '679'],
            ['nation' => 'Finlândia', 'ddi' => '358'],
            ['nation' => 'França', 'ddi' => '33'],
            ['nation' => 'Gabão', 'ddi' => '241'],
            ['nation' => 'Gâmbia', 'ddi' => '220'],
            ['nation' => 'Banda de Gaza (Palestina)', 'ddi' => '970'],
            ['nation' => 'Geórgia', 'ddi' => '995'],
            ['nation' => 'Gana', 'ddi' => '233'],
            ['nation' => 'Gibraltar', 'ddi' => '350'],
            ['nation' => 'Grécia', 'ddi' => '30'],
            ['nation' => 'Groelândia', 'ddi' => '299'],
            ['nation' => 'Granada', 'ddi' => '1 473'],
            ['nation' => 'Guam', 'ddi' => '1 671'],
            ['nation' => 'Guatemala', 'ddi' => '502'],
            ['nation' => 'Guiana', 'ddi' => '592'],
            ['nation' => 'Guiné', 'ddi' => '224'],
            ['nation' => 'Guiné Equatorial', 'ddi' => '240'],
            ['nation' => 'Guiné-Bissau', 'ddi' => '245'],
            ['nation' => 'Haiti', 'ddi' => '509'],
            ['nation' => 'Honduras', 'ddi' => '504'],
            ['nation' => 'Hong Kong', 'ddi' => '852'],
            ['nation' => 'Hungria', 'ddi' => '36'],
            ['nation' => 'Islândia', 'ddi' => '354'],
            ['nation' => 'Ilhas Cayman', 'ddi' => '1 345'],
            ['nation' => 'Ilhas Cocos (Keeling)', 'ddi' => '61'],
            ['nation' => 'Ilha de Man', 'ddi' => '44'],
            ['nation' => 'Ilhas Cook', 'ddi' => '682'],
            ['nation' => 'Ilhas Falkland (Malvinas)', 'ddi' => '500'],
            ['nation' => 'Ilhas Feroé', 'ddi' => '298'],
            ['nation' => 'Ilhas Mariana do Norte', 'ddi' => '1 670'],
            ['nation' => 'Ilhas Marshall', 'ddi' => '692'],
            ['nation' => 'Ilhas Norfolk', 'ddi' => '672'],
            ['nation' => 'Ilhas Pitcairn', 'ddi' => '870'],
            ['nation' => 'Ilhas Salomão', 'ddi' => '677'],
            ['nation' => 'Ilhas Turcas e Caicos', 'ddi' => '1 649'],
            ['nation' => 'Ilhas Virgens Americanas', 'ddi' => '1 340'],
            ['nation' => 'Ilhas Virgens Britânicas', 'ddi' => '1 284'],
            ['nation' => 'India', 'ddi' => '91'],
            ['nation' => 'Indonésia', 'ddi' => '62'],
            ['nation' => 'Inglaterra (Reino Unido)', 'ddi' => '44'],
            ['nation' => 'Irã', 'ddi' => '98'],
            ['nation' => 'Iraque', 'ddi' => '964'],
            ['nation' => 'Irlanda', 'ddi' => '353'],
            ['nation' => 'Israel', 'ddi' => '972'],
            ['nation' => 'Itália', 'ddi' => '39'],
            ['nation' => 'Jamaica', 'ddi' => '1 876'],
            ['nation' => 'Japão', 'ddi' => '81'],
            ['nation' => 'Jersey', 'ddi' => ''],
            ['nation' => 'Jordânia', 'ddi' => '962'],
            ['nation' => 'Cazaquistão', 'ddi' => '7'],
            ['nation' => 'Quénia (Kenya)', 'ddi' => '254'],
            ['nation' => 'Kiribati', 'ddi' => '686'],
            ['nation' => 'Kosovo', 'ddi' => '381'],
            ['nation' => 'Kuwait', 'ddi' => '965'],
            ['nation' => 'Quirguistão', 'ddi' => '996'],
            ['nation' => 'Laos', 'ddi' => '856'],
            ['nation' => 'Letônia', 'ddi' => '371'],
            ['nation' => 'Líbano', 'ddi' => '961'],
            ['nation' => 'Lesoto', 'ddi' => '266'],
            ['nation' => 'Libéria', 'ddi' => '231'],
            ['nation' => 'Líbia', 'ddi' => '218'],
            ['nation' => 'Liechtenstein', 'ddi' => '423'],
            ['nation' => 'Lituânia', 'ddi' => '370'],
            ['nation' => 'Luxemburgo', 'ddi' => '352'],
            ['nation' => 'Macau', 'ddi' => '853'],
            ['nation' => 'Macedónia', 'ddi' => '389'],
            ['nation' => 'Madagáscar', 'ddi' => '261'],
            ['nation' => 'Malawi', 'ddi' => '265'],
            ['nation' => 'Malásia', 'ddi' => '60'],
            ['nation' => 'Maldivas', 'ddi' => '960'],
            ['nation' => 'Mali', 'ddi' => '223'],
            ['nation' => 'Malta', 'ddi' => '356'],
            ['nation' => 'Mauritânia', 'ddi' => '222'],
            ['nation' => 'Maurícia', 'ddi' => '230'],
            ['nation' => 'Mayotte', 'ddi' => '262'],
            ['nation' => 'México', 'ddi' => '52'],
            ['nation' => 'Micronésia', 'ddi' => '691'],
            ['nation' => 'Moldávia', 'ddi' => '373'],
            ['nation' => 'Monaco', 'ddi' => '377'],
            ['nation' => 'Mongólia', 'ddi' => '976'],
            ['nation' => 'Montenegro', 'ddi' => '382'],
            ['nation' => 'Montserrat', 'ddi' => '1 664'],
            ['nation' => 'Marrocos', 'ddi' => '212'],
            ['nation' => 'Moçambique', 'ddi' => '258'],
            ['nation' => 'Namíbia', 'ddi' => '264'],
            ['nation' => 'Nauru', 'ddi' => '674'],
            ['nation' => 'Nepal', 'ddi' => '977'],
            ['nation' => 'Netherlands Antilles', 'ddi' => '599'],
            ['nation' => 'Nova Caledônia', 'ddi' => '687'],
            ['nation' => 'Nova Zelândia', 'ddi' => '64'],
            ['nation' => 'Nicaragua', 'ddi' => '505'],
            ['nation' => 'Níger', 'ddi' => '227'],
            ['nation' => 'Nigéria', 'ddi' => '234'],
            ['nation' => 'Niue', 'ddi' => '683'],
            ['nation' => 'Noruega', 'ddi' => '47'],
            ['nation' => 'Omã', 'ddi' => '968'],
            ['nation' => 'Países Baixos', 'ddi' => '31'],
            ['nation' => 'Paquistão', 'ddi' => '92'],
            ['nation' => 'Palau', 'ddi' => '680'],
            ['nation' => 'Panamá', 'ddi' => '507'],
            ['nation' => 'Papua-Nova Guiné', 'ddi' => '675'],
            ['nation' => 'Paraguai', 'ddi' => '595'],
            ['nation' => 'Peru', 'ddi' => '51'],
            ['nation' => 'Filipinas', 'ddi' => '63'],
            ['nation' => 'Polónia', 'ddi' => '48'],
            ['nation' => 'Polinésia Francesa', 'ddi' => '689'],
            ['nation' => 'Portugal', 'ddi' => '351'],
            ['nation' => 'Porto Rico', 'ddi' => '1'],
            ['nation' => 'República do Congo', 'ddi' => '242'],
            ['nation' => 'República Democrática do Congo', 'ddi' => '243'],
            ['nation' => 'República Centro-Africana', 'ddi' => '236'],
            ['nation' => 'República Checa', 'ddi' => '420'],
            ['nation' => 'República Dominicana', 'ddi' => '1 809'],
            ['nation' => 'Roménia', 'ddi' => '40'],
            ['nation' => 'Ruanda', 'ddi' => '250'],
            ['nation' => 'Rússia', 'ddi' => '7'],
            ['nation' => 'Saint Barthelemy', 'ddi' => '590'],
            ['nation' => 'Samoa', 'ddi' => '685'],
            ['nation' => 'Samoa Americana', 'ddi' => '1 684'],
            ['nation' => 'San Marino', 'ddi' => '378'],
            ['nation' => 'Sao Tome e Principe', 'ddi' => '239'],
            ['nation' => 'Senegal', 'ddi' => '221'],
            ['nation' => 'Serbia', 'ddi' => '381'],
            ['nation' => 'Serra Leoa', 'ddi' => '232'],
            ['nation' => 'Seychelles', 'ddi' => '248'],
            ['nation' => 'Slovakia', 'ddi' => '421'],
            ['nation' => 'Slovenia', 'ddi' => '386'],
            ['nation' => 'Somalia', 'ddi' => '252'],
            ['nation' => 'Sri Lanka', 'ddi' => '94'],
            ['nation' => 'Saint Helena', 'ddi' => '290'],
            ['nation' => 'Saint Kitts and Nevis', 'ddi' => '1 869'],
            ['nation' => 'Saint Lucia', 'ddi' => '1 758'],
            ['nation' => 'Saint Martin', 'ddi' => '1 599'],
            ['nation' => 'Saint Pierre and Miquelon', 'ddi' => '508'],
            ['nation' => 'Saint Vincent and the Grenadines', 'ddi' => '1 784'],
            ['nation' => 'Sudão', 'ddi' => '249'],
            ['nation' => 'Suriname', 'ddi' => '597'],
            ['nation' => 'Svalbard', 'ddi' => ''],
            ['nation' => 'Suazilândia', 'ddi' => '268'],
            ['nation' => 'Suécia', 'ddi' => '46'],
            ['nation' => 'Suiça', 'ddi' => '41'],
            ['nation' => 'Syria', 'ddi' => '963'],
            ['nation' => 'Taiwan', 'ddi' => '886'],
            ['nation' => 'Tajiquistão', 'ddi' => '992'],
            ['nation' => 'Tanzânia', 'ddi' => '255'],
            ['nation' => 'Timor-Leste', 'ddi' => '670'],
            ['nation' => 'Tailândia', 'ddi' => '66'],
            ['nation' => 'Togo', 'ddi' => '228'],
            ['nation' => 'Tokelau', 'ddi' => '690'],
            ['nation' => 'Tonga', 'ddi' => '676'],
            ['nation' => 'Trinidad e Tobago', 'ddi' => '1 868'],
            ['nation' => 'Tunísia', 'ddi' => '216'],
            ['nation' => 'Turquemenistão', 'ddi' => '993'],
            ['nation' => 'Turquia', 'ddi' => '90'],
            ['nation' => 'Tuvalu', 'ddi' => '688'],
            ['nation' => 'Uganda', 'ddi' => '256'],
            ['nation' => 'Ucrânia', 'ddi' => '380'],
            ['nation' => 'Uruguai', 'ddi' => '598'],
            ['nation' => 'Estados Unidos (EUA)', 'ddi' => '1'],
            ['nation' => 'Uzbequistão', 'ddi' => '998'],
            ['nation' => 'Vanuatu', 'ddi' => '678'],
            ['nation' => 'Vaticano', 'ddi' => '39'],
            ['nation' => 'Venezuela', 'ddi' => '58'],
            ['nation' => 'Vietnã (Vietname)', 'ddi' => '84'],
            ['nation' => 'Wallis e Futuna', 'ddi' => '681'],
            ['nation' => 'West Bank', 'ddi' => '970'],
            ['nation' => 'Western Sahara', 'ddi' => ''],
            ['nation' => 'Iémen (Iémen, Yemen)', 'ddi' => '967'],
            ['nation' => 'Zimbabwe(Zimbabué)', 'ddi' => '263'],
            ['nation' => 'Zâmbia', 'ddi' => '260']
        ]);
    }
}
